### ISSUE TITLE
[BUG] Color mixing percentage does not amount to 100%

### ISSUE THREAD

**Issue by thadogg** [Vertabreak/Marlin#223]
### Bug Description

When setting color mixing ratio with M163 command, adding up percentages showing up on LCD display equals 99% instead of 100% for some ratios

### My Configurations

[configuration.zip](https://github.com/Vertabreak/Marlin/files/4332130/configuration.zip)

### Steps to Reproduce

issue the following commands:
M163 S0 P0.5
M163 S1 P0.5
M164 S0

M163 S0 P1.0
M163 S1 P0.0
M164 S1

M163 S0 P0.25
M163 S1 P0.75
M164 S2

M163 S0 P0.68
M163 S1 P0.32
M164 S3

**Expected behavior:** [What you expect to happen]
When issuing "T0", LCD should display "Mx 50;50%"
When issuing "T1", LCD should display "Mx 100;0%"
When issuing "T2", LCD should display "Mx 25;75%"
When issuing "T3", LCD should display "Mx 68;32%"

**Actual behavior:** [What actually happens]
When issuing "T0", LCD displays "Mx 50;50%"
When issuing "T1", LCD displays "Mx 100;0%"
When issuing "T2", LCD displays "Mx 24;75%"
When issuing "T3", LCD displays "Mx 68;31%"

#### Additional Information
![scr](https://user-images.githubusercontent.com/23703409/76671296-b639df80-6595-11ea-9d61-d589825fa4cc.png)
![IMG_20200314_014733](https://user-images.githubusercontent.com/23703409/76671356-26e0fc00-6596-11ea-9790-b526ecaba9b8.jpg)

**Comment by Vertabreak** [comment]
source bug report there.
