### ISSUE TITLE
[BUG] freeze when changing extruder

### ISSUE THREAD

**Issue by 88mich** [Vertabreak/Marlin#234]
when the extruder changes during printing the printer stops, I noticed that it stops when it encounters the T1 command

![IMG_20200417_193757](https://user-images.githubusercontent.com/63873759/79601182-b3786000-80e8-11ea-86f3-83e0ee39a17e.jpg)

Printer geeetech A10M gt2560 v4.0

**Comment by Vertabreak** [comment]
File a bug report to marlin none of that code was written by me. The only 3 files that contain my code are configuration.h configuration_adv.h and start_here.h anything else is marlin. I maintain a custom configuration for marlin on this GitHub nothing more.

https://github.com/MarlinFirmware/Marlin

**Comment by 88mich** [comment]
sorry! ok thank you!

**Comment by Vertabreak** [comment]
he literally documented coding it on his channel to.
https://www.youtube.com/watch?v=SispDLjKXLI

**Comment by Vertabreak** [comment]
i have coded complete sets of vtools to be loaded at boot in my fork this should no longer be possible as you cant switch to a tool that does not exist.
