### ISSUE TITLE
Support GTM32 Pro VD

### ISSUE THREAD

**Issue by dasch3a** [Vertabreak/Marlin#236]
Hi,

I saw that your Software supports more Geeetech models. Is there also support for the GTM32 Pro VD? I did not see it in the src.

Greetings

David

**Comment by Vertabreak** [comment]
the VB and VD are the same as far as marlin gtm32 support is development only does not print.
in fact every gtm32 from the mini to the current vd are all the exact same in marlin.

**Comment by dasch3a** [comment]
So I could just choose the GTM32 VB instead of my GTM32 VD and it should be running? Or what do you want to say with "only does not print"?

**Comment by Vertabreak** [comment]
none of the gtm32 board are print ready in marlin its unfinished the pins file for VB covers nearly every gtm32 board there is no need to have many copy's that have each new name where geeetech made a tiny change and called it something new.
