### ISSUE TITLE
G29 J  resets printer

### ISSUE THREAD

**Issue by n00b42** [Vertabreak/Marlin#267]
### Description

`G29 J` resets the printer

### Steps to Reproduce

~~~
G28
G29 A
G29 L1
G29 J
~~~

**Expected behavior:**

Tilting 3 points.

**Actual behavior:**

~~~
Send: G29 J
Recv: //action:notification Doing G29
Recv: Tilting mesh (1/3)
Recv:  T:26.50 /0.00 B:25.48 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:26.50 /0.00 B:25.48 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:26.56 /0.00 B:25.45 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv: echo:start
Recv: Marlin Marlin 2 Bugfix Build 495
~~~

#### Additional Information

Config: [Marlin.zip](https://github.com/Vertabreak/Marlin/files/4833324/Marlin.zip)

Seems related to: https://github.com/MarlinFirmware/Marlin/issues/14575

**Comment by n00b42** [comment]
Should I report this issue upstream or could it be related to this fork?

**Comment by Vertabreak** [comment]
nothing to do with my configuration and all of my code is upstream anyways this is a marlin issue this fork is a flavor of config nothing more.
