### ISSUE TITLE
G29 Autolevel not work

### ISSUE THREAD

**Issue by przepka1985** [Vertabreak/Marlin#362]
My printer
Geeetech A10T
GT 2560 v4
TMC2208STD All
Genuine BL Touch 3.1
Runout Sensor x3
3 Extruders
MixT

### Description

G29 command dont work from terminal and from start gcode.

### Steps to Reproduce

1. I have check previous  ver 1.1.8 and autolevel working fine
2. After marlin 2 update something its missing in autolevel sector or bl touch sector

**Expected behavior:** Autolevel works

**Actual behavior:** Short beep from buzer (like click more than beep) And not move at all, on terminal i got an   echo:debug:info, errors    
but without any description
I was turn on debugging in autolevel section 

N19 G29*42
echo:N19 G29*42
Z Probe End Script: G1 X0 Y0

#### Additional Information

[Config.zip](https://github.com/Vertabreak/Marlin/files/5312751/Config.zip)

**Comment by Vertabreak** [comment]
G29 isn't a valid command UBL does not work this way zero start gcode of any kind is needed when used correctly.
This is 100% Pebkac error suggest reading the wiki & watching the video on my channel.
https://marlinfw.org/docs/gcode/G029-ubl.html
https://www.youtube.com/watch?v=4kSnoMjrAi8

**Comment by przepka1985** [comment]
Thats make sense :) 
I was use to 1.1.8 with bi linear.
Thanks Vert
