### ISSUE TITLE
Geeetech A10M - TMC2088 stepper drivers - Can't get inverting of the extruder to work

### ISSUE THREAD

**Issue by anaxagoras83** [Vertabreak/Marlin#366]
### Description

Hi, I was so happy to find your GitHub Repo because I could not get my A10M to work with the stock FW and you did an amazing job with the Start_here.h file and the user experience on my 3D printer. But unfortunately i cannot get the direction of the extruder to change. 

### Steps to Reproduce

I edited the start_here.c to customize it to my A10M. I could change the directions of the XYZ axis but the Extruder still runs backwards wehen sending positive values. 

I tried several attempts to invert the extruder direction on Line 210 with commenting the line out and enabeling it. But the direction of the extruder does not change.

#define INVERTE     // enable false / disabe true to change direction

#### Additional Information

[Marlin.zip](https://github.com/Vertabreak/Marlin/files/5323052/Marlin.zip)

**Comment by Vertabreak** [comment]
this is my personal version of marlin for my personal use suggest using upstream marlin.
i don't offer any unpaid support and at this time no donation options are offered.
i'm going to disable the issue section totally after this post.
